name: MysticNavigator
version: 2.0
main: me.s1mple.MysticNavigator
depend: [WorldEdit, FastAsyncWorldEdit]
commands:
    mn:
      description: Default command.
      aliases: [mysticnavigator, navi]
    mna:
      description: Default command for resetting arenas.
      aliases: [mysticnavigatorarena, naviarena]